export const CHANGE_ROURE = "CHANGE_ROURE";

export const REQUEST_DAILY_LIMIT = "REQUEST_DAILY_LIMIT";
export const RECEIVE_DAILY_LIMIT = "RECEIVE_DAILY_LIMIT";

export const REQUEST_UPDATE_DAILY_LIMIT = "REQUEST_UPDATE_DAILY_LIMIT";
export const RECEIVE_UPDATE_DAILY_LIMIT = "RECEIVE_UPDATE_DAILY_LIMIT";

export const REQUEST_TODAY_RECORD = "REQUEST_TODAY_RECORD";
export const RECEIVE_TODAY_RECORD = "RECEIVE_TODAY_RECORD";

export const REQUEST_DECREASE_TODAY_RECORD = "REQUEST_DECREASE_TODAY_RECORD";
export const RECEIVE_DECREASE_TODAY_RECORD = "RECEIVE_DECREASE_TODAY_RECORD";
